# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudflare-ddns" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "b37b9ae98a1b0fd4f8f10ddf53f009f1a62d06e615770fbe3ffd75e94ce31a19"
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v#{version}/cloudflare-ddns_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b32442890323e425e55a12ffc1b11e39ed2670787dacb6169c35976d312d4eca"
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v#{version}/cloudflare-ddns_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca3a5c987487b1c44918303ef5bb0e0dbb6085de2f3ac2d9db9575a177927703"
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v#{version}/cloudflare-ddns_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "07051a238284f9784926822a4fcad73a7639a06b9d1db1e3fb828eed943e64c9"
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v#{version}/cloudflare-ddns_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cloudflare-ddns"
  desc "Sync a Cloudflare DNS record with your current public IP address"
  homepage "https://github.com/gabe565/cloudflare-ddns"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudflare-ddns"
  manpage "manpages/cloudflare-ddns.1.gz"
  bash_completion "completions/cloudflare-ddns.bash"
  fish_completion "completions/cloudflare-ddns.fish"
  zsh_completion "completions/cloudflare-ddns.zsh"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloudflare-ddns"]
    end
  end

  # No zap stanza required
end
