# This file was generated by nightscout-menu-bar's release workflow. DO NOT EDIT.
cask "nightscout-menu-bar" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "298374e0613f88244e98c0ff30c92394ffe1c555df58b29a6df8f67e6e3b7ee1"
      url "https://github.com/gabe565/nightscout-menu-bar/releases/download/v#{version}/nightscout-menu-bar_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bdc747d193c625bb0402985a49a4003b4efc0f92328595cd76d1986fb15785a"
      url "https://github.com/gabe565/nightscout-menu-bar/releases/download/v#{version}/nightscout-menu-bar_darwin_amd64.tar.gz"
    end

    app "Nightscout Menu Bar.app"
  end
  on_linux do
    on_arm do
      sha256 "17331f09f7700d69a240866f2a448fffc36cab86bdcd9e921e0f3e199375f039"
      url "https://github.com/gabe565/nightscout-menu-bar/releases/download/v#{version}/nightscout-menu-bar_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a731e6f3b5874c5b0f8fc7873850203e99a9a27781365de14450536fa47855e3"
      url "https://github.com/gabe565/nightscout-menu-bar/releases/download/v#{version}/nightscout-menu-bar_linux_amd64.tar.gz"
    end

    binary "nightscout-menu-bar"
  end

  name "Nightscout Menu Bar"
  desc "Display live blood sugar data from Nightscout in your system menu bar"
  homepage "https://github.com/gabe565/nightscout-menu-bar"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/Nightscout Menu Bar.app"]
    end
  end

  zap trash: [
    "~/.config/autostart/com.gabe565.nightscout-menu-bar.desktop",
    "~/.config/nightscout-menu-bar",
    "~/Library/Application Support/nightscout-menu-bar",
    "~/Library/LaunchAgents/com.gabe565.nightscout-menu-bar.plist",
  ]
end
