# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ansi2txt < Formula
  desc "Convert text containing ANSI control codes into plain ASCII text."
  homepage "https://github.com/gabe565/ansi2txt"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/ansi2txt/releases/download/v0.0.1/ansi2txt_0.0.1_darwin_amd64.tar.gz"
      sha256 "56ad888b437361b1e46f79b33a9fc32e6f8b2481ff772dfff8836d2f612297f5"

      def install
        bin.install "ansi2txt"
      end
    end
    on_arm do
      url "https://github.com/gabe565/ansi2txt/releases/download/v0.0.1/ansi2txt_0.0.1_darwin_arm64.tar.gz"
      sha256 "58333629017f922dc8eb7d35d9afbcbac97b8b157bf95e2393b4c32c439561a9"

      def install
        bin.install "ansi2txt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/ansi2txt/releases/download/v0.0.1/ansi2txt_0.0.1_linux_amd64.tar.gz"
        sha256 "6c97a80690bd3c2b0127e9d44526a01b3fefafc2ec3a6c998c2349a0e86ac218"

        def install
          bin.install "ansi2txt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/ansi2txt/releases/download/v0.0.1/ansi2txt_0.0.1_linux_arm64.tar.gz"
        sha256 "45c436d7b229fdce6d2e5dcdd727a3d1be26b9b4ad4b4bfacb557f04a4569d36"

        def install
          bin.install "ansi2txt"
        end
      end
    end
  end
end
