# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ansi2txt < Formula
  desc "Convert text containing ANSI control codes into plain ASCII text."
  homepage "https://github.com/gabe565/ansi2txt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/ansi2txt/releases/download/v0.1.0/ansi2txt_0.1.0_darwin_amd64.tar.gz"
      sha256 "f7605fee2e85f65f4234dda0654d02f3cdde58c496e1b56058861c66c81fda25"

      def install
        bin.install "ansi2txt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/ansi2txt/releases/download/v0.1.0/ansi2txt_0.1.0_darwin_arm64.tar.gz"
      sha256 "188b54ab907f1c70e19a38fb49894d87f50ba9352e2970ae07466eb1421b1540"

      def install
        bin.install "ansi2txt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/ansi2txt/releases/download/v0.1.0/ansi2txt_0.1.0_linux_amd64.tar.gz"
        sha256 "63d042dfeb8a9d33d3f007d1ec1958a8bca22577515f30adc565aa8d572d86ac"

        def install
          bin.install "ansi2txt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/ansi2txt/releases/download/v0.1.0/ansi2txt_0.1.0_linux_arm64.tar.gz"
        sha256 "22b2e16124997c91ffb90fdebc8e20ff622a11aac7fed130d81c5e46fb7cdd8b"

        def install
          bin.install "ansi2txt"
        end
      end
    end
  end
end
