# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiMovie < Formula
  desc "Star Wars SSH + Telnet server written in Go"
  homepage "https://github.com/gabe565/ascii-movie"
  version "1.7.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.7.1/ascii-movie_1.7.1_darwin_arm64.tar.gz"
      sha256 "32ef575e8037a5846ab1d6356d5b2a943ae773bf4e4e38cd082b1b8a93a9c471"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.7.1/ascii-movie_1.7.1_darwin_amd64.tar.gz"
      sha256 "c6f738bece5413cd2d38b252dbae80fd8eaba9ef8b29fd9b37169f247168e032"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.7.1/ascii-movie_1.7.1_linux_amd64.tar.gz"
      sha256 "b5a2cbf889a7adcd4f9fe6b01208f4284458cb3f9f4f6f083667ae8502f07a3c"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.7.1/ascii-movie_1.7.1_linux_arm64.tar.gz"
      sha256 "1311c9886a622177771886e3b3a8cbbcc2cb33b9dbb5bf269d7280dd618e6aae"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
  end
end
