# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiMovie < Formula
  desc "Star Wars SSH + Telnet server written in Go"
  homepage "https://github.com/gabe565/ascii-movie"
  version "1.8.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.8.1/ascii-movie_1.8.1_darwin_amd64.tar.gz"
      sha256 "4bcb7ad96b2fbc3971b1e2b2b589c01e383fcbbcb00321385f5dd5b3cfe7a447"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.8.1/ascii-movie_1.8.1_darwin_arm64.tar.gz"
      sha256 "539eaac75d1772d18ba8365e677334c7da27c1ce211e09d8d111d3d05a058507"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.8.1/ascii-movie_1.8.1_linux_amd64.tar.gz"
      sha256 "262ad3f44ef7ec441c3354e598127b4f4d1876e00d5b056918f94c0932845d8d"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/ascii-movie/releases/download/v1.8.1/ascii-movie_1.8.1_linux_arm64.tar.gz"
      sha256 "06323293fd31dd9d7462a9ecd42222cbe8e7e239a566c1e31a6d8c7afff13915"

      def install
        bin.install "ascii-movie"
        man1.install "manpages/ascii-movie.1.gz"
        man1.install "manpages/ascii-movie-get.1.gz"
        man1.install "manpages/ascii-movie-get-stream.1.gz"
        man1.install "manpages/ascii-movie-ls.1.gz"
        man1.install "manpages/ascii-movie-play.1.gz"
        man1.install "manpages/ascii-movie-serve.1.gz"
        bash_completion.install "completions/ascii-movie.bash" => "ascii-movie"
        zsh_completion.install "completions/ascii-movie.zsh" => "_ascii-movie"
        fish_completion.install "completions/ascii-movie.fish"
      end
    end
  end
end
