# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Castsponsorskip < Formula
  desc "Skip YouTube ads and sponsorships on all local Google Cast devices"
  homepage "https://github.com/gabe565/CastSponsorSkip"
  version "0.7.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.7.4/castsponsorskip_0.7.4_darwin_arm64.tar.gz"
      sha256 "0f76c94c621d044f500f8588003941985fbbe4c25f4f9e1303f31855d8a53826"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.7.4/castsponsorskip_0.7.4_darwin_amd64.tar.gz"
      sha256 "bbb9d971949ebb5a6b567e324405f55d7e7d1beff92430e34b9f58e802f07fbc"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.7.4/castsponsorskip_0.7.4_linux_armv6.tar.gz"
      sha256 "95fdef16cc52531ffa080456569d385d6fcacd598520aa69c094a8d4cb223fed"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.7.4/castsponsorskip_0.7.4_linux_arm64.tar.gz"
      sha256 "840364e1c7ac054ef90940c9d43f7f257702305cb2b70b88f08754345f6d8519"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.7.4/castsponsorskip_0.7.4_linux_amd64.tar.gz"
      sha256 "e594ca11d528c8794177bb1f50813678c61a0bfbd4c1786af3f1a2a1b5f66f2d"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
  end

  service do
    if OS.linux?
      name "systemd/castsponsorskip.service"
    else
      run [opt_bin/"castsponsorskip"]
      keep_alive true
      error_log_path var/"log/castsponsorskip.log"
    end
  end
end
