# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Castsponsorskip < Formula
  desc "Skip sponsored YouTube content on all local Google Cast devices"
  homepage "https://github.com/gabe565/CastSponsorSkip"
  version "0.3.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.3.1/castsponsorskip_0.3.1_darwin_amd64.tar.gz"
      sha256 "9df8775c38769609f397b48a1d8ba603c248902e31a921178437db979a24f03e"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.3.1/castsponsorskip_0.3.1_darwin_arm64.tar.gz"
      sha256 "e21b35054195bd1c907d669409dee068dcdb9594c4ecc87805177c00885699fb"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.3.1/castsponsorskip_0.3.1_linux_armv6.tar.gz"
      sha256 "4d45d8945739d9ed34729c699ef3613dda1171c72df53d472a2fd5ce11a306f7"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.3.1/castsponsorskip_0.3.1_linux_amd64.tar.gz"
      sha256 "5cb0f2d81e2c0601d466c6210da0fb4fc79ef913f050c31036ecfcce61888bfa"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/CastSponsorSkip/releases/download/v0.3.1/castsponsorskip_0.3.1_linux_arm64.tar.gz"
      sha256 "a981ff7bbaaba34613b383bc923cb5dd1020788dc33052836f3ec375419c24ea"

      def install
        bin.install "castsponsorskip"
        man1.install "manpages/castsponsorskip.1.gz"
        bash_completion.install "completions/castsponsorskip.bash" => "castsponsorskip"
        zsh_completion.install "completions/castsponsorskip.zsh" => "_castsponsorskip"
        fish_completion.install "completions/castsponsorskip.fish"
      end
    end
  end

  service do
    if OS.linux?
      name "systemd/castsponsorskip.service"
    else
      run [opt_bin/"castsponsorskip"]
      keep_alive true
      error_log_path var/"log/castsponsorskip.log"
    end
  end
end
