# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogGenerator < Formula
  desc "Generates a changelog from commits since the previous release."
  homepage "https://github.com/gabe565/changelog-generator"
  version "1.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.4/changelog-generator_1.1.4_darwin_amd64.tar.gz"
      sha256 "e33c73de45d0bf455e14fab1b03b420f8c711a7d702213bb65b1d3652ba36db8"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.4/changelog-generator_1.1.4_darwin_arm64.tar.gz"
      sha256 "503a30598c861ca578a15b940bfbc6c04923c7c08bb7c1756720be8840426222"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.4/changelog-generator_1.1.4_linux_amd64.tar.gz"
        sha256 "29aa1fd56a0ff705d3c6be5754402aeaaa98ba4dcecec61afe065a54cbdf79d0"

        def install
          bin.install "changelog-generator"
          man1.install "manpages/changelog-generator.1.gz"
          bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
          zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
          fish_completion.install "completions/changelog-generator.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.4/changelog-generator_1.1.4_linux_arm64.tar.gz"
        sha256 "1a6b936ec63300b6ad4e58372618b649597e5006fbc9faebb64468d4795f0a5b"

        def install
          bin.install "changelog-generator"
          man1.install "manpages/changelog-generator.1.gz"
          bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
          zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
          fish_completion.install "completions/changelog-generator.fish"
        end
      end
    end
  end
end
