# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogGenerator < Formula
  desc "Generates a changelog from commits since the previous release."
  homepage "https://github.com/gabe565/changelog-generator"
  version "1.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.2/changelog-generator_1.1.2_darwin_amd64.tar.gz"
      sha256 "4cce3cf22a409da1f6b05276b617b5005ed40a486b4c53cb12ed1dca1f836b55"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
    on_arm do
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.2/changelog-generator_1.1.2_darwin_arm64.tar.gz"
      sha256 "1fa3f183ee682c71b771a6c18c3a15dd5d5f5abc1bbe4ea228afe2b5985d32f1"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.2/changelog-generator_1.1.2_linux_amd64.tar.gz"
        sha256 "58f1d033f188f32d5faa879f00871ff9f741aa02337df320296aa453856a62ad"

        def install
          bin.install "changelog-generator"
          man1.install "manpages/changelog-generator.1.gz"
          bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
          zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
          fish_completion.install "completions/changelog-generator.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/changelog-generator/releases/download/v1.1.2/changelog-generator_1.1.2_linux_arm64.tar.gz"
        sha256 "156a3b03c947ec14532b4592aa70e6e2474ce33b74af8d07af972ab0d99ad6eb"

        def install
          bin.install "changelog-generator"
          man1.install "manpages/changelog-generator.1.gz"
          bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
          zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
          fish_completion.install "completions/changelog-generator.fish"
        end
      end
    end
  end
end
