# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogGenerator < Formula
  desc "Generates a changelog from commits since the previous release."
  homepage "https://github.com/gabe565/changelog-generator"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.0.0/changelog-generator_1.0.0_darwin_amd64.tar.gz"
      sha256 "e3c4fc6282279c90ba293e976da755ad9526036b0183bec8da5669f1eff7f69c"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.0.0/changelog-generator_1.0.0_darwin_arm64.tar.gz"
      sha256 "048112fcbb5e530452c5e4b66eeeb723351ac2180604e2602dad2fd2e79452b3"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.0.0/changelog-generator_1.0.0_linux_amd64.tar.gz"
      sha256 "f0cfa337102ce338da2f4cf7f8c9286f8c2d45e76daae403640ddf29dea8ad7a"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/changelog-generator/releases/download/v1.0.0/changelog-generator_1.0.0_linux_arm64.tar.gz"
      sha256 "2ab9570dbde4e422f3f95541e50b40eabe4d6cb67df8a4fae095d921e0965839"

      def install
        bin.install "changelog-generator"
        man1.install "manpages/changelog-generator.1.gz"
        bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
        zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
        fish_completion.install "completions/changelog-generator.fish"
      end
    end
  end
end
