# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliOfLife < Formula
  desc "Play Conways Game of Life in your terminal"
  homepage "https://github.com/gabe565/cli-of-life"
  version "0.4.0"
  license "Apache2"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/cli-of-life/releases/download/v0.4.0/cli-of-life_0.4.0_darwin_amd64.tar.gz"
      sha256 "3b285dbb180046d7ea0a78fe7bf24cbab55be6eaeb17d96cf74708bc1cb5d3a6"

      def install
        bin.install "cli-of-life"
        man1.install "manpages/cli-of-life.1.gz"
        bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
        zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
        fish_completion.install "completions/cli-of-life.fish"
      end
    end
    on_arm do
      url "https://github.com/gabe565/cli-of-life/releases/download/v0.4.0/cli-of-life_0.4.0_darwin_arm64.tar.gz"
      sha256 "8c4680c86e217c6cb357d15d30989273f89052e612ba62a70b49d66fb61f5441"

      def install
        bin.install "cli-of-life"
        man1.install "manpages/cli-of-life.1.gz"
        bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
        zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
        fish_completion.install "completions/cli-of-life.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cli-of-life/releases/download/v0.4.0/cli-of-life_0.4.0_linux_amd64.tar.gz"
        sha256 "81e545c1f7a9a2395c9e7363aa9defcff6e54aaff5c5b67c2af20cbf1b562efa"

        def install
          bin.install "cli-of-life"
          man1.install "manpages/cli-of-life.1.gz"
          bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
          zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
          fish_completion.install "completions/cli-of-life.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cli-of-life/releases/download/v0.4.0/cli-of-life_0.4.0_linux_arm64.tar.gz"
        sha256 "26b05e73e237cc409d698843d2a42ba910ff0dfd7bdf54db4ce19690f241ed74"

        def install
          bin.install "cli-of-life"
          man1.install "manpages/cli-of-life.1.gz"
          bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
          zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
          fish_completion.install "completions/cli-of-life.fish"
        end
      end
    end
  end
end
