# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliOfLife < Formula
  desc "Play Conways Game of Life in your terminal"
  homepage "https://github.com/gabe565/cli-of-life"
  version "0.1.1"
  license "Apache2"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/cli-of-life/releases/download/v0.1.1/cli-of-life_0.1.1_darwin_amd64.tar.gz"
      sha256 "0932394fe37f54c1193863b94ec5c3aabd76b3b1cd65b08ccc615086de73f510"

      def install
        bin.install "cli-of-life"
        man1.install "manpages/cli-of-life.1.gz"
        bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
        zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
        fish_completion.install "completions/cli-of-life.fish"
      end
    end
    on_arm do
      url "https://github.com/gabe565/cli-of-life/releases/download/v0.1.1/cli-of-life_0.1.1_darwin_arm64.tar.gz"
      sha256 "b4bbaaccef15a0e0be9b9d9ef1972b9147dbcfbbee69196dbdb305a22e19529c"

      def install
        bin.install "cli-of-life"
        man1.install "manpages/cli-of-life.1.gz"
        bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
        zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
        fish_completion.install "completions/cli-of-life.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cli-of-life/releases/download/v0.1.1/cli-of-life_0.1.1_linux_amd64.tar.gz"
        sha256 "23e5d1bdb2bf4bb564fd51c506b5e216c6bbe6bbf69702e8a614c2e270cd54fb"

        def install
          bin.install "cli-of-life"
          man1.install "manpages/cli-of-life.1.gz"
          bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
          zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
          fish_completion.install "completions/cli-of-life.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cli-of-life/releases/download/v0.1.1/cli-of-life_0.1.1_linux_arm64.tar.gz"
        sha256 "40696e8359456ec2f0ed712e88dcbe6f6c66b7850b1b090199c8ddf462e47b02"

        def install
          bin.install "cli-of-life"
          man1.install "manpages/cli-of-life.1.gz"
          bash_completion.install "completions/cli-of-life.bash" => "cli-of-life"
          zsh_completion.install "completions/cli-of-life.zsh" => "_cli-of-life"
          fish_completion.install "completions/cli-of-life.fish"
        end
      end
    end
  end
end
