# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareDdns < Formula
  desc "Sync a Cloudflare DNS record with your current public IP address"
  homepage "https://github.com/gabe565/cloudflare-ddns"
  version "0.2.0"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v0.2.0/cloudflare-ddns_0.2.0_darwin_amd64.tar.gz"
      sha256 "f9ec5bbb3379cd8bd2f1829e08bffef17f8ce390e523834689f7626788cdf452"

      def install
        bin.install "cloudflare-ddns"
        man1.install "manpages/cloudflare-ddns.1.gz"
        bash_completion.install "completions/cloudflare-ddns.bash" => "cloudflare-ddns"
        zsh_completion.install "completions/cloudflare-ddns.zsh" => "_cloudflare-ddns"
        fish_completion.install "completions/cloudflare-ddns.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/cloudflare-ddns/releases/download/v0.2.0/cloudflare-ddns_0.2.0_darwin_arm64.tar.gz"
      sha256 "88ffeab40d0b2b0faed13c0b66fbd912e49c5730c822811b38efea5daeb4f031"

      def install
        bin.install "cloudflare-ddns"
        man1.install "manpages/cloudflare-ddns.1.gz"
        bash_completion.install "completions/cloudflare-ddns.bash" => "cloudflare-ddns"
        zsh_completion.install "completions/cloudflare-ddns.zsh" => "_cloudflare-ddns"
        fish_completion.install "completions/cloudflare-ddns.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cloudflare-ddns/releases/download/v0.2.0/cloudflare-ddns_0.2.0_linux_amd64.tar.gz"
        sha256 "fb99b0245c45fbcc2f4888745db48e0c55d39163607b808b24e3d831eae141a4"

        def install
          bin.install "cloudflare-ddns"
          man1.install "manpages/cloudflare-ddns.1.gz"
          bash_completion.install "completions/cloudflare-ddns.bash" => "cloudflare-ddns"
          zsh_completion.install "completions/cloudflare-ddns.zsh" => "_cloudflare-ddns"
          fish_completion.install "completions/cloudflare-ddns.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/cloudflare-ddns/releases/download/v0.2.0/cloudflare-ddns_0.2.0_linux_arm64.tar.gz"
        sha256 "5ca2540a4203a2059e10cc549bc7ce03aa61732fa268edad2218a857e80e4f00"

        def install
          bin.install "cloudflare-ddns"
          man1.install "manpages/cloudflare-ddns.1.gz"
          bash_completion.install "completions/cloudflare-ddns.bash" => "cloudflare-ddns"
          zsh_completion.install "completions/cloudflare-ddns.zsh" => "_cloudflare-ddns"
          fish_completion.install "completions/cloudflare-ddns.fish"
        end
      end
    end
  end
end
