# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DomainWatch < Formula
  desc "Get notified about domain changes as they happen"
  homepage "https://github.com/gabe565/domain-watch"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_darwin_arm64.tar.gz"
      sha256 "860a158c51e31cf4a0cceaf5c00cc143ca02e6ac7f49d3b5e54fd6f5c552c927"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_darwin_amd64.tar.gz"
      sha256 "8e93a06027f33925b23520c94267e71a7376ff8aa795db5b8dda616eb37d22f9"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_arm64.tar.gz"
      sha256 "f0a9940be6d06a9003bb78641d0a943ecd7036cdc42cc81f79a91108ccaa7254"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_amd64.tar.gz"
      sha256 "f0bc490f67a946408bef34c86c7d960f39fa8ef5aa09bd6870a1c280e9586f3b"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_armv6.tar.gz"
      sha256 "63f9a6caa176147155a987ede5d2ed1c76bb7294c622783bc254f74c88716c73"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
  end
end
