# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DomainWatch < Formula
  desc "Get notified about domain changes as they happen"
  homepage "https://github.com/gabe565/domain-watch"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_darwin_arm64.tar.gz"
      sha256 "c1b20edc3e095d39e1ca4bb9996eb9d07d536900de2ffab7f2ee7e8f86ec9e84"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_darwin_amd64.tar.gz"
      sha256 "a22031f6a4d60ab9eb316893f6fb942b29974e5e7829d3e260a1d225f1092be9"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_armv6.tar.gz"
      sha256 "83972ff4b532143f370e9952c9139690455cfaa297d400cda1c13fbb2d40f16a"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_amd64.tar.gz"
      sha256 "d99ebe44ea344883a6c3aa94b2aa85f19dea1d91bb3580e75794e91dbaa2ebe2"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.1.0/domain-watch_0.1.0_linux_arm64.tar.gz"
      sha256 "f6cde40795eed75c1f41dff0a4b7df366e659bcde61732336994a19a5fce0c71"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
  end
end
