# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DomainWatch < Formula
  desc "Get notified about domain changes as they happen"
  homepage "https://github.com/gabe565/domain-watch"
  version "0.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.2.0/domain-watch_0.2.0_darwin_amd64.tar.gz"
      sha256 "6284ad3247fd0f3bb663b21fad59310282b560af75a14f8c524224bbbdd1b296"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/domain-watch/releases/download/v0.2.0/domain-watch_0.2.0_darwin_arm64.tar.gz"
      sha256 "241d88a5004f54960c51ddd8a868bcdbddb758b7da39687459ca8de137ba48e3"

      def install
        bin.install "domain-watch"
        man1.install "manpages/domain-watch.1.gz"
        bash_completion.install "completions/domain-watch.bash" => "domain-watch"
        zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
        fish_completion.install "completions/domain-watch.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/domain-watch/releases/download/v0.2.0/domain-watch_0.2.0_linux_amd64.tar.gz"
        sha256 "cb8bdb4694f9bd6b6b7d8a2339643845802c6b07f33c76af4cb0f7b72989b7a1"

        def install
          bin.install "domain-watch"
          man1.install "manpages/domain-watch.1.gz"
          bash_completion.install "completions/domain-watch.bash" => "domain-watch"
          zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
          fish_completion.install "completions/domain-watch.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/domain-watch/releases/download/v0.2.0/domain-watch_0.2.0_linux_armv6.tar.gz"
        sha256 "fb4c37f53f2285da613ad156e3d268620c35045dfdccba7ec31da5f0cf8d1dff"

        def install
          bin.install "domain-watch"
          man1.install "manpages/domain-watch.1.gz"
          bash_completion.install "completions/domain-watch.bash" => "domain-watch"
          zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
          fish_completion.install "completions/domain-watch.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/domain-watch/releases/download/v0.2.0/domain-watch_0.2.0_linux_arm64.tar.gz"
        sha256 "a97becaaf02cb989614d0ede1f00d27d0351db63c4a536a0e0aa26efb531d2d9"

        def install
          bin.install "domain-watch"
          man1.install "manpages/domain-watch.1.gz"
          bash_completion.install "completions/domain-watch.bash" => "domain-watch"
          zsh_completion.install "completions/domain-watch.zsh" => "_domain-watch"
          fish_completion.install "completions/domain-watch.fish"
        end
      end
    end
  end
end
