# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoreutilsGo < Formula
  desc "A Go rewrite of moreutils: A collection of the Unix tools that nobody thought to write long ago when Unix was young."
  homepage "https://github.com/gabe565/moreutils"
  version "0.2.0"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/moreutils/releases/download/v0.2.0/moreutils-go_0.2.0_darwin_amd64.tar.gz"
      sha256 "dd78f62e70386de1bc1ecb6c3facc85e096f152fea3e0e14dd61084e7d269182"

      def install
        bin.install "moreutils"
        bin.install Dir["links/*"]

        man1.install Dir["manpages/*"]

        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
    on_arm do
      url "https://github.com/gabe565/moreutils/releases/download/v0.2.0/moreutils-go_0.2.0_darwin_arm64.tar.gz"
      sha256 "263541ba0d7f20e98d643a6e9229b5894f3b2ff8261a6bf960d816d6de3ae340"

      def install
        bin.install "moreutils"
        bin.install Dir["links/*"]

        man1.install Dir["manpages/*"]

        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/moreutils/releases/download/v0.2.0/moreutils-go_0.2.0_linux_amd64.tar.gz"
        sha256 "69342e8a6664ad3ec77320a1b614196319b0a6617a4132fec679ad78230e60ae"

        def install
          bin.install "moreutils"
          bin.install Dir["links/*"]

          man1.install Dir["manpages/*"]

          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/moreutils/releases/download/v0.2.0/moreutils-go_0.2.0_linux_arm64.tar.gz"
        sha256 "713ad922ba64935eeacc5cf09a6462509487b7afaa7057e41ea69eb114594aef"

        def install
          bin.install "moreutils"
          bin.install Dir["links/*"]

          man1.install Dir["manpages/*"]

          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
  end
end
