# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoreutilsGo < Formula
  desc "A Go rewrite of moreutils: A collection of the Unix tools that nobody thought to write long ago when Unix was young."
  homepage "https://github.com/gabe565/moreutils"
  version "0.5.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/moreutils-go/releases/download/v0.5.1/moreutils-go_0.5.1_darwin_amd64.tar.gz"
      sha256 "e1f4e33b2dfa284adc20866cca96d89203e42d1ee1cf761e895216429f990000"

      def install
        bin.install "moreutils"
        bin.install Dir["links/*"]

        man1.install Dir["manpages/*"]

        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/moreutils-go/releases/download/v0.5.1/moreutils-go_0.5.1_darwin_arm64.tar.gz"
      sha256 "42285c15eca292dce6b2c535b7d0c2668e6353ac36009d1246438a1272f6aa70"

      def install
        bin.install "moreutils"
        bin.install Dir["links/*"]

        man1.install Dir["manpages/*"]

        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/moreutils-go/releases/download/v0.5.1/moreutils-go_0.5.1_linux_amd64.tar.gz"
        sha256 "544526e083eb7d2242f324a678862fdff71dc7692d94abb57c5a14469deff2f8"

        def install
          bin.install "moreutils"
          bin.install Dir["links/*"]

          man1.install Dir["manpages/*"]

          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/moreutils-go/releases/download/v0.5.1/moreutils-go_0.5.1_linux_arm64.tar.gz"
        sha256 "91bdb693d0ac2f3dc7714e9fbb8cedd4577b2bbebec2152ae7751353fb27e751"

        def install
          bin.install "moreutils"
          bin.install Dir["links/*"]

          man1.install Dir["manpages/*"]

          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
  end
end
