# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PwgenGo < Formula
  desc "Command line passphrase generator written in Go"
  homepage "https://github.com/gabe565/pwgen-go"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.4.1/pwgen-go_0.4.1_darwin_amd64.tar.gz"
      sha256 "0fd2ad4f9543b1ad504790b7a9a1b0add80ebeb3fb9f48dc80c194a97342ff6d"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
    on_arm do
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.4.1/pwgen-go_0.4.1_darwin_arm64.tar.gz"
      sha256 "aebdf9ab01a5020fbdc64c1ab89f83ef6bb180c0444e21b6be76953ee91ddaaf"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/pwgen-go/releases/download/v0.4.1/pwgen-go_0.4.1_linux_amd64.tar.gz"
        sha256 "3fc0a6c09fe50a9510cc9954172ece1cce0e0ae030a9bf95d6b458faa14e770a"

        def install
          bin.install "pwgen"
          man1.install "manpages/pwgen.1.gz"
          bash_completion.install "completions/pwgen.bash" => "pwgen"
          zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
          fish_completion.install "completions/pwgen.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/pwgen-go/releases/download/v0.4.1/pwgen-go_0.4.1_linux_arm64.tar.gz"
        sha256 "cb12b2944e8fcf1a770e67caf9080c3f68866a835bcd65dda03dfbc61efa6960"

        def install
          bin.install "pwgen"
          man1.install "manpages/pwgen.1.gz"
          bash_completion.install "completions/pwgen.bash" => "pwgen"
          zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
          fish_completion.install "completions/pwgen.fish"
        end
      end
    end
  end
end
