# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PwgenGo < Formula
  desc "Command line passphrase generator written in Go"
  homepage "https://github.com/gabe565/pwgen-go"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.8.0/pwgen-go_0.8.0_darwin_amd64.tar.gz"
      sha256 "969a2d71200e5f202ac418de6c72d41b6e86b7e5e335616000955aaaa8d49f38"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.8.0/pwgen-go_0.8.0_darwin_arm64.tar.gz"
      sha256 "e6e10c8dfc1545fd6507775a40984ff03bbf54efb0808aee44b92f481b83bb7a"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.8.0/pwgen-go_0.8.0_linux_amd64.tar.gz"
      sha256 "0a0ef6bd7e694ede452bb9b740f67295c63d7c83ad0bc2c932fb32a43a576071"
      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.8.0/pwgen-go_0.8.0_linux_arm64.tar.gz"
      sha256 "b24ac66d271e68f64fcc2e7f26010ac2d376d6e5c44f5809c3642a275cf4a683"
      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
  end
end
