# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PwgenGo < Formula
  desc "Command line passphrase generator written in Go"
  homepage "https://github.com/gabe565/pwgen-go"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.1.1/pwgen-go_0.1.1_darwin_amd64.tar.gz"
      sha256 "ba4ed547b418533a8276b45e3295cee96addf9ffdfe4dd2fa026a0de62889902"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.1.1/pwgen-go_0.1.1_darwin_arm64.tar.gz"
      sha256 "9c0f00624d2f2444b7e920e27bfb2754277816fbcb3a67eb3a1d901d81a005e6"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.1.1/pwgen-go_0.1.1_linux_arm64.tar.gz"
      sha256 "125d2900c9ee8fa81509b5ed82c72decebc1caa8b026186b23939c34c110b13a"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/pwgen-go/releases/download/v0.1.1/pwgen-go_0.1.1_linux_amd64.tar.gz"
      sha256 "f4f8ab1580083048ad27763bdf1d20a5e73005c80238699edadc6b541d96fca4"

      def install
        bin.install "pwgen"
        man1.install "manpages/pwgen.1.gz"
        bash_completion.install "completions/pwgen.bash" => "pwgen"
        zsh_completion.install "completions/pwgen.zsh" => "_pwgen"
        fish_completion.install "completions/pwgen.fish"
      end
    end
  end
end
