# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubcablemapDl < Formula
  desc "Download full-resolution versions of Telegeography Submarine Cable Maps"
  homepage "https://github.com/gabe565/subcablemap-dl"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabe565/subcablemap-dl/releases/download/v0.3.0/subcablemap-dl_0.3.0_darwin_amd64.tar.gz"
      sha256 "4800db30e11256ed4bb46019d2623333ab007c80c379f30ada54ccda238b8ec8"

      def install
        bin.install "subcablemap-dl"
        man1.install "manpages/subcablemap-dl.1.gz"
        bash_completion.install "completions/subcablemap-dl.bash" => "subcablemap-dl"
        zsh_completion.install "completions/subcablemap-dl.zsh" => "_subcablemap-dl"
        fish_completion.install "completions/subcablemap-dl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabe565/subcablemap-dl/releases/download/v0.3.0/subcablemap-dl_0.3.0_darwin_arm64.tar.gz"
      sha256 "528328092025d8003016112c7da56844d57e2c5e426819b0a7b7c697ee79ae71"

      def install
        bin.install "subcablemap-dl"
        man1.install "manpages/subcablemap-dl.1.gz"
        bash_completion.install "completions/subcablemap-dl.bash" => "subcablemap-dl"
        zsh_completion.install "completions/subcablemap-dl.zsh" => "_subcablemap-dl"
        fish_completion.install "completions/subcablemap-dl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/subcablemap-dl/releases/download/v0.3.0/subcablemap-dl_0.3.0_linux_amd64.tar.gz"
        sha256 "af8e0777c3a3403d5a4d368f0566dea09f83fea20f2891d563305e5285f51cb2"

        def install
          bin.install "subcablemap-dl"
          man1.install "manpages/subcablemap-dl.1.gz"
          bash_completion.install "completions/subcablemap-dl.bash" => "subcablemap-dl"
          zsh_completion.install "completions/subcablemap-dl.zsh" => "_subcablemap-dl"
          fish_completion.install "completions/subcablemap-dl.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/subcablemap-dl/releases/download/v0.3.0/subcablemap-dl_0.3.0_linux_arm64.tar.gz"
        sha256 "f14fe41a0b8d07327f619a658ac2c509e83f2a84a39efec44b6e2dcb53065272"

        def install
          bin.install "subcablemap-dl"
          man1.install "manpages/subcablemap-dl.1.gz"
          bash_completion.install "completions/subcablemap-dl.bash" => "subcablemap-dl"
          zsh_completion.install "completions/subcablemap-dl.zsh" => "_subcablemap-dl"
          fish_completion.install "completions/subcablemap-dl.fish"
        end
      end
    end
  end
end
