# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebosDevMode < Formula
  desc "A command-line tool to extend the webOS dev mode session timer"
  homepage "https://github.com/gabe565/webos-dev-mode"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gabe565/webos-dev-mode/releases/download/v0.0.1/webos-dev-mode_0.0.1_darwin_amd64.tar.gz"
      sha256 "86f6645ff6bb6af9f33af8347b9d3001d7815a24bd1c708a767d6e0f1ab21a97"

      def install
        bin.install "webos-dev-mode"
        man1.install "manpages/webos-dev-mode.1.gz"
        bash_completion.install "completions/webos-dev-mode.bash" => "webos-dev-mode"
        zsh_completion.install "completions/webos-dev-mode.zsh" => "_webos-dev-mode"
        fish_completion.install "completions/webos-dev-mode.fish"
      end
    end
    on_arm do
      url "https://github.com/gabe565/webos-dev-mode/releases/download/v0.0.1/webos-dev-mode_0.0.1_darwin_arm64.tar.gz"
      sha256 "3085faef49fab32fb2192609f2727d0e9a2fb281c05216ea5a29d7a3548516fa"

      def install
        bin.install "webos-dev-mode"
        man1.install "manpages/webos-dev-mode.1.gz"
        bash_completion.install "completions/webos-dev-mode.bash" => "webos-dev-mode"
        zsh_completion.install "completions/webos-dev-mode.zsh" => "_webos-dev-mode"
        fish_completion.install "completions/webos-dev-mode.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/webos-dev-mode/releases/download/v0.0.1/webos-dev-mode_0.0.1_linux_amd64.tar.gz"
        sha256 "4128ee7ad6543c6d0ef036627cd1769d08cdda805e45ff08184eec0eae4683e4"

        def install
          bin.install "webos-dev-mode"
          man1.install "manpages/webos-dev-mode.1.gz"
          bash_completion.install "completions/webos-dev-mode.bash" => "webos-dev-mode"
          zsh_completion.install "completions/webos-dev-mode.zsh" => "_webos-dev-mode"
          fish_completion.install "completions/webos-dev-mode.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabe565/webos-dev-mode/releases/download/v0.0.1/webos-dev-mode_0.0.1_linux_arm64.tar.gz"
        sha256 "bb512eb986063966eae5452d6a650c97df71d6e27ee2e9e9832c3741483f53bb"

        def install
          bin.install "webos-dev-mode"
          man1.install "manpages/webos-dev-mode.1.gz"
          bash_completion.install "completions/webos-dev-mode.bash" => "webos-dev-mode"
          zsh_completion.install "completions/webos-dev-mode.zsh" => "_webos-dev-mode"
          fish_completion.install "completions/webos-dev-mode.fish"
        end
      end
    end
  end
end
